version: "3"

services:
  squid-proxy:
    image: sameersbn/squid:3.5.27-2
    container_name: squid
    restart: always
    ports:
    - 3128:3128
    volumes:
    - /opt/squid/cache:/var/spool/squid
    - ./squid.conf:/etc/squid/squid.conf
